var sistemaEspecialista = {
    R1: [{
        "nao": "R2",
        "sim": "R8",
        "pergunta": "É menino?",
        "foto_sim": null,
        "foto_nao": null,
    }],
    R2: [{
        "nao": "R3",
        "sim": "Nicole",
        "pergunta": "É loira?",
        "foto_sim": "nicole",
        "foto_nao": null,
    }],
    R3: [{
        "nao": "R4",
        "sim": "R5",
        "pergunta": "Usa óculos?",
        "foto_sim": null,
        "foto_nao": null,
    }],
    R4: [{
        "nao": "Jéssica",
        "sim": "Raquel",
        "pergunta": "Tem tatuagens?",
        "foto_sim": "raquel",
        "foto_nao": "jessica",
    }],
    R5: [{
        "nao": "R6",
        "sim": "R7",
        "pergunta": "Tinha casaco igual de outras meninas?",
        "foto_sim": null,
        "foto_nao": null,
    }],
    R6: [{
        "nao": "Marina",
        "sim": "Duda",
        "pergunta": "Tinha casaco fofo de apertar?",
        "foto_sim": "Duda",
        "foto_nao": "Marina",
    }],
    R7: [{
        "nao": "Giulia",
        "sim": "Raianne",
        "pergunta": "É alta?",
        "foto_sim": "raianne",
        "foto_nao": "giulia",
    }],
    R8: [{
        "nao": "R9",
        "sim": "R11",
        "pergunta": "Tem cabelo preto?",
        "foto_sim": null,
        "foto_nao": null,
    }],
    R9: [{
        "nao": "R10",
        "sim": "R12",
        "pergunta": "Tem cabelo crespo?",
        "foto_sim": null,
        "foto_nao": null,
    }],
    R10: [{
        "nao": "Felipe",
        "sim": "Matheus",
        "pergunta": "Tem Pebble?",
        "foto_sim": "matheus",
        "foto_nao": "felipe",
    }],
    R11: [{
        "nao": "Eduardo",
        "sim": "Guilherme",
        "pergunta": "Tem Pebble?",
        "foto_sim": "guilherme",
        "foto_nao": "eduardo",
    }],
    R12: [{
        "nao": "R13",
        "sim": "Caio",
        "pergunta": "Tem tatuagens?",
        "foto_sim": "caio",
        "foto_nao": null,
    }],
    R13: [{
        "nao": "Bruno",
        "sim": "Michelangelo",
        "pergunta": "Tem olhos claros?",
        "foto_sim": "michelangelo",
        "foto_nao": "bruno",
    }]
};